### ISSUE TITLE
Set strategy on how to vendor code from LPE into PQ

### ISSUE THREAD

**Issue by peter-mlabs** [Liqwid-Labs/plutarch-quickcheck#28]
PQ2.0 has some dependence on LPE, but we use PQ to test LPE.

Currently, the relevant functions are copied into the modules where they are needed. This may be acceptable, but is probably suboptimal in a few ways. In an effort merge #27, this issue is being created to remind us to investigate a better solution. 

I think, at a minimum, it would be better to have these functions vendored in their own modules (like `Plutarch.Extra.Maybe`) and use `PackageImports` to differentiate whenever necessary, rather than having them co-mingled in the modules where they are used.

**Comment by peter-mlabs** [comment]
Assigning Koz to set the strategy; either myself or @SeungheonOh can implement it once a decision is made.

**Comment by SeungheonOh** [comment]
Dumping PQ into LPE would be a decent option, because, in the future, I think there might be more use of LPE utilities in PQ. When we get `EvaluatedTerm` in LPE, we'll definitely use that in PQ and et cetera.

**Comment by kozross** [comment]
This is a somewhat tricky question, because I don't think there's a good choice here. Merging PQ with LPE is an option, but not a great one IMHO, because the whole point is that LPE is tested with PQ.

For the utilities I have seen used, I think 'keep local copies for now, upstream to Plutarch itself' is the best move. However, I am unsure exactly how easy this will be, how receptive they will be, and how specialized the utilities in question are.

**Comment by peter-mlabs** [comment]
Okay. Let's make local modules in PQ, make ample notes, and upstream. Thanks, Koz.
